# Generated by Django 3.1.2 on 2020-10-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_auto_20201019_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=1, max_length=80),
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
