# Generated by Django 3.1.2 on 2020-10-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_auto_20201017_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
    ]
